# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
        stages: [commit]
      - id: check-json
        stages: [commit]
      - id: check-toml
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: check-case-conflict
        stages: [commit]
      - id: detect-private-key
        stages: [commit]
      # - id: end-of-file-fixer
      - id: check-added-large-files
        stages: [commit]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.2
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
  - repo: https://github.com/crate-ci/committed
    rev: v1.0.20
    hooks:
      - id: committed
        stages: [commit-msg]
