style = "conventional"
ignore_author_re = "(dependabot|renovate)"
allowed_types = [
    "chore",
    "ci",
    "docs",
    "feat",
    "fix",
    "perf",
    "refactor",
    "style",
    "test",
]
subject_capitalized = false
merge_commit = false
no_fixup = false
no_wip = false
