from typing import Any

objs: Any
indices: Any

def change(field: Any, before: Any, after: Any): ...
def typechange(field: Any, before: Any, after: Any): ...
def added(field: Any, after: Any): ...
def removed(field: Any, before: Any): ...
def test_compare(i1: Any, i2: Any, facit: Any) -> None: ...
def test_diff_equal(data: Any) -> None: ...
