from typing import Any

JSON_DATA: Any

def reference_dict(x: Any): ...
def convert_to_decimal_if_float(x: Any): ...
def assert_equal_not_none(i1: Any, i2: Any) -> None: ...
def compare_iters(it1: Any, it2: Any) -> None: ...
