from sb_json_tools import exceptions as exceptions

class JsonValidatorException(exceptions.JsonToolsException): ...
class SchemaDefinitionException(JsonValidatorException): ...
class ValidationException(JsonValidatorException): ...
