from typing import Any

TYPE: str
PATH: str
VALUE: str

class Diff:
    difference: Any = ...
    seen: Any = ...
    def __init__(self, first: Any, second: Any, with_values: bool = ...) -> None: ...
    def check(self, first: Any, second: Any, path: str = ..., with_values: bool = ...) -> None: ...
    def save_diff(self, path: Any, diff_before: Any, diff_after: Any, type_: Any) -> None: ...

def get_content(location: Any): ...
def compare_gen(location1: Any, location2: Any, print_all: bool = ...) -> None: ...
def compare(location1: Any, location2: Any, print_all: bool = ...): ...
